### ISSUE TITLE
Add Badges to the Top of the README

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#101]
The project currently has a badge at the very bottom of the README. This should be moved to the top. Also, the integration should be with CodeCov.io instead of Coveralls. Finally, you should add extra badges that report, for instance, the status of the build.

**Comment by gkapfham** [comment]
Yes, @huangs1, correct, these issues go together. Once that issue is resolved, then we will need to leverage the fact that the reporting works and then create the badges. There is already an example of this working:

https://github.com/GatorEducator/gatorgrader

**Comment by huangs1** [comment]
@gkapfham I believe we need permission to actually be able to run codecov for this repository. I have requested access already, but I just wanted confirm that that was the way to go with this issue.

**Comment by Lancasterwu** [comment]
This issue has been resolved.
