### ISSUE TITLE
Reconfigure Travis CI so That is Uses Pipenv

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#103]
The Travis CI configuration given in the README file is out of date in regards to the current standards for using Travis CI. This content should also be thoroughly revised so that it uses Pipenv for dependency management.

**Comment by ilikerustoo** [comment]
I have successfully integrated Pipenv in Travis CI

**Comment by Lancasterwu** [comment]
This issue has been resolved.
