### ISSUE TITLE
Test with Multiple Versions of Python Using Pyenv and Tox

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#105]
The tool is currently only being tested with an old version of Python. First, we should start developing and testing according to the features of a new version of Python. Next, we need to start performing test suite runs with multiple version of Python in Travis CI. I suggest that we investigate the combined used of Pyenv and Tox to support this type of testing. Overall, this type of testing will better ensure that our tool works for a wide variety of people who are using this tool

**Comment by reibelj** [comment]
```reibelj@aldenv166:~/cs203/gatorgrouper$ pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main```


When trying to run the program for the first time, this is the error I received from having a lower version of Python. To remedy this error, I upgraded Python and reinstalled pyenv.

**Comment by reibelj** [comment]
```
reibelj@aldenv166:~/cs203/gatorgrouper$ python3 gatorgrouper.py

GatorGrouper: Automatically Assign Students to Groups
https://github.com/GatorGrouper/gatorgrouper

Traceback (most recent call last):
  File "gatorgrouper.py", line 33, in <module>
    create_csv()
  File "/home/r/reibelj/cs203/gatorgrouper/spreadsheet.py", line 25, in create_csv
    sheet = client.open(DEFAULT_WORKBOOK).sheet1
  File "/home/r/reibelj/.local/lib/python3.7/site-packages/gspread/client.py", line 123, in open
    self.list_spreadsheet_files()
  File "/home/r/reibelj/.local/lib/python3.7/site-packages/gspread/client.py", line 96, in list_spreadsheet_files
    res = self.request('get', url, params=params).json()
  File "/home/r/reibelj/.local/lib/python3.7/site-packages/gspread/client.py", line 79, in request
    raise APIError(response)
gspread.exceptions.APIError: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission: Request had insufficient authentication scopes."
   }
  ],
  "code": 403,
  "message": "Insufficient Permission: Request had insufficient authentication scopes."
 }
}
```

There are several issues with the program that prevent it from running. This makes the issue of testing very difficult until these errors are resolved.
@Lancasterwu

**Comment by ilikerustoo** [comment]
I can help with this. @Lancasterwu  @reibelj do you have anything so far?

**Comment by reibelj** [comment]
I am still looking into this issue. @Lancasterwu  and I will work on it tomorrow during our meeting. Let us know if you make any further progress on this issue.

**Comment by Lancasterwu** [comment]
Hi, @ilikerustoo Thanks for asking. We have tested `pyenv` with python version 3.6.8 and 3.7.2. We also tried to run with Python 2.7, and of course, it did not work. Instead of testing it with Travis CI, we were manually testing it with `pyenv` to download different versions of Python. 
Do you want to take care of the `Tox` package? https://tox.readthedocs.io/en/latest/ 
When we meet tomorrow, we can implement the test of both packages with Travis CI together.

**Comment by ilikerustoo** [comment]
````
jobs:
  include:
    - env: TOXENV=py34
      python: '3.4'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py36
      python: '3.6'
````

Add to Travis.yml

**Comment by Lancasterwu** [comment]
@ilikerustoo Thanks

**Comment by ilikerustoo** [comment]
Currently I have 3 instances of python up and working. `3.4`, `3.5`, and `3.6`.

**Comment by ilikerustoo** [comment]
This has been through Travis instead of to or pyenv

**Comment by Lancasterwu** [comment]
This issue has been resolved.
