### ISSUE TITLE
Provide a Sample CSV File to Support Initial Exploration

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#106]
The repository does not provide an example of a CSV file for which a person can use as input when running the sample instructions. This makes it really difficult for a person to use the examples in the README file. We should provide a sample CSV file in an appropriate sub-directory and then use this as part of any examples.

**Comment by gkapfham** [comment]
It is important to note that adding this CSV file might require us to either adjust the `.gitignore` file or to force-add this file.

**Comment by Lancasterwu** [comment]
This issue will be closed because the class decided to use json instead of csv.

**Comment by Lancasterwu** [comment]
Never mind, we still need a sample CSV to run the program, in order to resolve the issue like https://github.com/GatorEducator/gatorgrouper/issues/105 Also, the error message like 
```
Traceback (most recent call last):
  File "gatorgrouper.py", line 33, in <module>
    create_csv()
  File "/home/w/wuj/cs203S2019/lab/gatorgrouper/spreadsheet.py", line 25, in create_csv
```
Is also probably due to the CSV.

**Comment by Lancasterwu** [comment]
We can actually run the program without `create_csv`.
