### ISSUE TITLE
Perform Robustness Testing with Hypothesis

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#112]
While GatorGrouper currently has a high coverage test suite, it is good idea for us to perform additional testing, perhaps by using a tool like Hypothesis to generate random input values. These tests could be marked separately and, perhaps, not during during the Travis CI build. However, this new type of testing could be useful for finding hard-to-discover bugs in "corner cases" of, for instance, parameter verification.

**Comment by libailong** [comment]
https://hypothesis.readthedocs.io/en/latest/
This website helps a lot to get a general understanding of Hypothesis.
https://hypothesis.readthedocs.io/en/latest/data.html
This tells us what we can generate from the Hypothesis. I am working on the test for text_display.py and try to figure out what type of input is for display and how to generate that? Do you guys have any ideas?

**Comment by mmarconi** [comment]
https://scipy-lectures.org/packages/statistics/index.html#id13
Here is another link with some info about Hypothesis testing in Python

**Comment by huangs1** [comment]
This should not have been closed since we still need to create more hypothesis tests to be more confident in the robustness for more functions. My team is currently working on creating more test cases using hypothesis, there should be a PR that will fix this issue soon.
