### ISSUE TITLE
Explain How to Install Python with Pyenv

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#115]
It is possible that people with have difficult installing and using GatorGrouper because they do not know how to install Python on their machine. While #81 suggests that we add a graphical user interface, and I agree that this is a good idea, we will have to focus first on finishing the tool and supporting the programmers who want to use it. This means that the README file should have documentation that explains how to setup a Python development environment, perhaps with Pyenv.

**Comment by Lancasterwu** [comment]
This is finished in https://github.com/GatorEducator/gatorgrouper/pull/123 by the whole Team "Lancaster" with members @reibelj @thomad74 @wattob @ALEXANDERB82 @everitt-andrew @Lancasterwu . The pull request is https://github.com/GatorEducator/gatorgrouper/pull/123.

**Comment by Michionlion** [comment]
We should keep in mind that this tool may be used by people in a Windows environment, and so `pyenv` or similar tools are not supported. Does your fix in #123 support this? If not, perhaps a separate issue can be opened to address that. In the meantime, since this issue is resolved, I'll close this.

**Comment by Lancasterwu** [comment]
@Michionlion Hi, I think we suggested people to upgrade the python version by downloading from the official website. If they can not, they can try use `pyenv`. We also mentioned in different development environment the situation may be different such as the configuration files. I think it is probably the solution for that. What is your opinion?

**Comment by Michionlion** [comment]
@Lancasterwu you could explicitly talk about the difference in Windows installation. However, if you feel like you've covered everything already, then that should be fine.
