### ISSUE TITLE
Do Not Require Editing of Source Code to Use

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#116]
The current README file explains that you have to edit source code in order to configure the interaction with the Google Sheet. While I am advising that we delete this code, as per #97, we should also make sure that the tool never requires a person to edit the source code in order to run the tool.

**Comment by aubreypc** [comment]
This is a major issue, installation should be as straightforward as possible. I propose that we use environment variables for any keys or API tokens. We can write a setup script which runs automatically after pip install to set up the default values, and have a script with some kind of command-line interface for updating the env variables with keys.

This also has the benefit of making it impossible for any keys to get committed (see issue #121 )
