### ISSUE TITLE
Add Flake8 and Pylint and Other Linting Tools Directly to Travis CI

### ISSUE THREAD

**Issue by Lancasterwu** [GatorEducator/gatorgrouper#124]
There are 2 lines of `tests/test_flake8.py` was not covered. Also, Gatorgrouper is using `coveralls.io` to show the code coverage, should we change it to `codecov.io` so we can easily know which line wasn't covered?

**Comment by Lancasterwu** [comment]
@gkapfham I think it is the great idea to just put linting into the Travis CI. The test cases should be more specific to some features of the program. Since I am personally interested in code coverage, I will go ahead to do some research and use `codecov.io` to replace `coveralls.io`.
Also, should I create another issue to be more specific abut  adding Flake8 and Pylint and other linting tools directly to Travis CI?

**Comment by gkapfham** [comment]
Hi @Lancasterwu, I think that you could potentially keep this issue but rename it so that it better fits your goals. You should also make sure that a team leader approves your work on this task.

**Comment by ilikerustoo** [comment]
While working on issue #103, I have configured Travis CI to use pylint and and flake8. I did this as the tools could not be implemented without converting the project to `pipenv` which is what I worked on and adding the tools was a simple job. @Lancasterwu If there are any other tools, let me know.

**Comment by aubreypc** [comment]
@ilikerustoo It might be a good idea to add black as well -- looks like it has a ``--check`` flag which just causes it to verify that the files do not need to be reformatted.

**Comment by ilikerustoo** [comment]
@aubreypc I already have that configuration in our fork so we are good

**Comment by Lancasterwu** [comment]
This issue has been resolved.
