### ISSUE TITLE
Use Type Hints in Order to Manage Complexity of Python's Dynamic Typing

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#128]
Python is a dynamically typed language, meaning we don't have to specify whether a variable is a string, int, list, tuple, etc. when we define it, and we can reassign the type of a variable freely. While dynamic typing can be very convenient, it can also cause problems when a function receives an argument of an unexpected type. For example:
```python
def shout(phrase):
    return phrase + "!"

>>> shout("hello")
"hello!"
>>> shout(1)
TypeError: cannot concatenate 'str' and 'int' objects
```

Python 3 introduces type hints, an optional syntax for describing the types of variables/arguments and return types of functions:

```python
def shout(phrase: str) -> str: # Takes a string and returns a string
    return phrase + "!"
```

The author of this [blog post on type hints](https://medium.com/@shamir.stav_83310/the-other-great-benefit-of-python-type-annotations-896c7d077c6b) points out a few benefits of using them:

1. There are tools such as [mypy](https://github.com/python/mypy) which can find type errors without even running the code. This could potentially lower the workload of writing test cases to manually check types. We could configure a tool like this to run as part of the Travis build process.

2. Explicitly indicating argument types and function return types makes the code easier to read and understand --- it's "self-documenting".

I suggest that we make use of type hints in our project. Since they are optional, we can find a balance by only using them in certain contexts --- maybe only for function definitions, and not for variables? Thoughts are welcome on this!

**Comment by paladp** [comment]
I think this is a great idea. I think that having them for function definitions to start with is good, and we can see if it's needed for variables as well. Should my team put this as a rule/principle in the complexity standards?

**Comment by aubreypc** [comment]
@paladp That sounds good to me!

**Comment by gkapfham** [comment]
Hi @aubreypc and @paladp, thanks for starting this discussion. I'm wondering whether it might be a good idea to pick a module of the system that is non-obvious and/or likely to be heavily modified and invest the time of adding type hints there? My reason for suggesting this is that type hints my not be as helpful and thus a time sink in code that we do not plan to modify during this project. But, if the code is complex and likely to see significant modifications, then maybe type hints might help.

Also, please be aware of the following project:

https://github.com/Instagram/MonkeyType
