### ISSUE TITLE
Implement a Scrum Framework to Manage Project Goals and Deadlines

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#130]
## What's Scrum?

A very silly word -- but besides that, **Scrum** is a system for managing projects, breaking up goals into concrete tasks, setting expectations, and ensuring that team members know what each other are working on. It's a way of implementing **agile development**, a corporate buzzword which basically just describes the goal of our class: form self-organized teams which adapt to unclear goals and changing circumstances. 

More details below, but here's my point: **without a clear workflow for assigning tasks and planning out where the project is headed, teamwork might become a source of complexity. Adopting Scrum would be the best way to give direction to GatorGrouper by streamlining the design and development processes.** (Plus, for those considering software development as a career, experience with a Scrum workflow is great to have!)

## How does Scrum work?

For a more full explanation, see [this article](https://medium.com/ideas-by-crema/the-4-scrum-ceremonies-made-simple-a-quick-guide-to-scrum-meetings-ea91fe604d88). Here's a quick summary:

### Scrum Roles

- The **Product Manager** is the person who makes executive decisions about the product. This person is kind of a liason between the users and the developers --- their job is to understand the needs of the users and translate those needs into concrete development tasks.
- The **Scrum Master** is responsible for communicating with others to get everyone on the same page and facilitating the completion of the current tasks. We would probably want one on each team. Having team leaders serve as scrum masters may be easiest.
- The **Development Team** is everyone else: developers, testers, designers, documentation writers, etc.

### The Scrum Workflow

The whole process lasts a week (or 2, if we'd rather do that). Here's how it works:

- **Planning**: The product manager and the development teams discuss the tasks which are currently prioritized, and negotiate with each other on a **sprint goal**, a concrete list of tasks which should be feasible to complete in the week. As part of this process, developers can advocate for themselves to **make sure the workload is reasonable and fairly distributed.**
- **Sprint:** The sprint lasts for the rest of the week. The goal is to finish the sprint goals, using **strategic programming** rather than tactical programming --- finishing an increment of maintainable, tested, production-ready code.
- **Scrum Meetings:** teams *briefly* (5 mins?) meet at the start of every class session. All team members share the following:
  - what they did since last session
  - what they plan to do between now and next session
  - what obstacles they are facing on their tasks
- **Sprint Review:** at the end of the sprint, teams meet to have a postmortem discussion and talk about what to do differently for the next sprint. The whole class also meet so teams can talk about and (if they want) give demonstrations of their accomplishments. I'm thinking that we could devote part of our lab sessions to the sprint review for the previous sprint and planning for the next sprint.

If people think this is a good idea in general, then we can begin to work out the details: sprint schedule, roles, etc.
Feel free to share any questions, comments, or suggestions!

**Comment by chenc-allegheny** [comment]
Maybe after the Scrum meeting, Scrum Masters(team leaders) should also briefly explain the progress of their teams to the Product Manager, to the CEO, to the class.

I also think that it would be very helpful if we can have a job-handover meeting, so that we know what the previous developers were thinking, for example, explain more on the Round-robin Grouping Method, other things that they have done besides the codes, maybe a user preference survey..... (If that is not too much to ask...)

**Comment by aubreypc** [comment]
@chenc-allegheny I like those ideas! The product manager will definitely have to work closely with the team leaders in order to track the progress of the sprint. Another feature which might help with this is [GitHub project boards](https://help.github.com/articles/about-project-boards/), giving a general overview of which issues and features are being worked on and how much work is remaining.  The job-handover meeting is also a great suggestion which would help avoid the problem of obscurity of the code.

**Comment by gkapfham** [comment]
This ideas sound great. We need to decide if this is gaining enough traction among team members that you want to adopt it going forward next week. I also agree that the project boards is a good idea. While we don't want to over-complicate our process, the team is pretty big and we need to get a clear sense of who is working on what and when they can finish those tasks.

**Comment by aubreypc** [comment]
@gkapfham Thanks for your feedback! I think I will go ahead and create a configure a project board so that we can have that before the next lab session. I posted a request for comments in the Slack channel, but didn't receive many -- do you think it would be best to just take a poll on whether to implement Scrum or not?

As for your comment about over-complicating our process, that is definitely a possible concern. If we end up doing Scrum, it may be best to keep the meetings as concise  as possible so that the framework facilitates our work rather than slowing it down.

**Comment by gkapfham** [comment]
HI @aubreypc, if you do not get feedback from developers about what step is the best, perhaps you can request feedback in-person on Monday. If there is no consensus after that point, then the team leaders will need to decide and then move forward to the completion of requirements elicitation and analysis and then design and implementation.

**Comment by quigley-c** [comment]
I like most of the ideas expressed in this proposition, however I don't know if sprint goals need to be slated quite as short as they are. I think some of us are too busy to be able to implement features in a single day, or less depending on the time of the next class session (I'm thinking of normal Wed - Fri being one day in-between, with lab Tues shortening the time further). Perhaps we could have sprint goals go from lab to lab, giving a whole week for achieving tasks?

**Comment by aubreypc** [comment]
@quigley-c The sprint goals would be from lab to lab, the daily meetings are just to gauge progress and make sure things are on track
