### ISSUE TITLE
Add Integration with Sakai 

### ISSUE THREAD

**Issue by enpuyou** [GatorEducator/gatorgrouper#131]
Since GatorGrouper will be used by instructors and professors, it will be a good idea if we can add integration with Sakai.

**Comment by Lancasterwu** [comment]
Hi @enpuyou, I think it is an excellent suggestion! However, I am wondering if it is too complicated for us to integrate. We probably should reach this person (hmccull@allegheny.edu) to see if there is some way for us to add features to Sakai.

**Comment by enpuyou** [comment]
Thank you @Lancasterwu, it is also chenc-allegheny's(chenc@allegheny.edu) idea. It would be great if you can also assign this issue to her. Somehow I can't @ her in this comment. Overall, that's a great idea.

**Comment by Lancasterwu** [comment]
@enpuyou Unfortunately, I can only assign the issue to people who post the issue, collaborators and the individual from the GatorEducator organization. Sorry about that.

**Comment by Michionlion** [comment]
It seems she is not a part of the organization. Should I invite @chenc-allegheny?

**Comment by enpuyou** [comment]
Yes! She is also part of the class! @Michionlion. Thank you!

**Comment by chenc-allegheny** [comment]
Thank you~ @Michionlion I guess that is probably because I have two school emails(cchen & chenc)....I think on the official student roster, I am cchen@allegheny.edu, at least, that is what I use to login to my WebAdvisor, but I use chenc more often. I also use chenc for my github account. It's complicated.

**Comment by gkapfham** [comment]
Hello @enpuyou, I don't think that this should be an initial goal for our team.
