### ISSUE TITLE
Add a license file for the project

### ISSUE THREAD

**Issue by wattob** [GatorEducator/gatorgrouper#138]
Hello, we currently do not have a license for the GatorGrouper project. Do any of you have a preference for which license we should select for this project? My suggestion is either the MIT License or the GNU General Public License. After the decision is made I can add it in my next Pull Request.

**Comment by thomad74** [comment]
What a great idea! I just created a LICENSE.md file for the GatorGrader tool in another class that contained a GNU General Public License. If that is the license that is decided on by @gkapfham and @Michionlion , I would be happy to assist with this issue!

**Comment by aubreypc** [comment]
Good suggestion! [This website](https://choosealicense.com/licenses/) may be helpful, as it offers concise summaries of the terms of different software licenses.

**Comment by Lancasterwu** [comment]
https://choosealicense.com/
The license probably gonna be GNU General Public License v3.0.
We are going to make a PR for this and write description of why we choose this license.
