### ISSUE TITLE
Allow users to log in with Google / GitHub

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#145]
In order to simplify the login process, we should use OAuth to allow users to sign in with their existing Google or GitHub accounts.

This blog post might help: https://medium.com/trabe/oauth-authentication-in-django-with-social-auth-c67a002479c1

Additionally, we could allow professors to configure their courses to add a college domain name, so that users who have an email with that domain attached to their Google account are allowed to join the course.

**Comment by quigley-c** [comment]
What kind of functionality did you want from this feature? What do we need to implement to this end? For now should we just set up the basic login scheme?

**Comment by aubreypc** [comment]
@quigley-c Here's some more info about the specific tasks I had in mind:

- Finding and installing a Django library which allows for OAuth / OpenID authentication
- Performing any necessary configuration to get this library to work with Google / GitHub (getting tokens, etc) 
- Writing some kind of User database model which associates an authenticated Google / GitHub account with the existing Professor/Student models
    - Ideally a user should be able to be both a professor and a student in different courses
- Writing views to handle the login process, integrating with the OAuth / OpenID library and with Django's built in authentication framework
- Integrating these login views with the design team's templates
- When progress has been made on #160, certain views should require a user to be logged in / enrolled in a particular course / the owner of a particular course
- Once views have been implemented for joining a course, professors should be able to configure a setting which allows any user whose Google / GitHub account email matches a specified domain name to join the course

And here are some links which might help:
- [A tutorial for the social-app-django OAuth / OpenID library](https://medium.com/trabe/oauth-authentication-in-django-with-social-auth-c67a002479c1)
- [A tutorial on using Django's built in auth system](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Authentication) -- the login and registration stuff won't be relevant, but e.g. we will likely use the `login_required` decorator on our views.
- [Using OAuth with GitHub](https://developer.github.com/apps/building-oauth-apps/)
- [Using OpenID with Google](https://developers.google.com/identity/protocols/OpenIDConnect)
