### ISSUE TITLE
Store secret keys securely

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#146]
Before eventually deploying our web application, we will want to find a way to keep any secret keys out of the repository -- perhaps with environment variables? -- so that nothing sensitive becomes publicly visible on GitHub.

**Comment by ilikerustoo** [comment]
I believe I figured out the way to do this. Please see my branch [hide-secret-key](https://github.com/GatorEducator/gatorgrouper/tree/bugfix/hide-secret-key)

**Comment by szklenskij** [comment]
@ilikerustoo fixed this issued in pull request `Bugfix/fixing bugs in develop` #159 which I approved for merge
