### ISSUE TITLE
Read from a JSON file instead of a CSV

### ISSUE THREAD

**Issue by paladp** [GatorEducator/gatorgrouper#163]
Currently GatorGrouper reads from a CSV file, for the purposes of future proofing we should change the program to read from a JSON file instead. This should be relatively easy, since the changes needed should be limited to the `read_student_file.py`

**Comment by szklenskij** [comment]
Should we close this issue if we've decided it is no longer going to be worked on?

**Comment by Alex-Yarkosky** [comment]
Due to the lack of benefits we would gain from using JSON instead of CSV and the time constraint with the deadline of the Ides of March, the issue has been given the `wont-fix` label and will therefore not be worked on in the near future.
