### ISSUE TITLE
The issue Template is Not Working correctly

### ISSUE THREAD

**Issue by Lancasterwu** [GatorEducator/gatorgrouper#183]
Related to [Issue#125](https://github.com/GatorEducator/gatorgrouper/issues/125) which supposed to be solved by [PR#149](https://github.com/GatorEducator/gatorgrouper/pull/149).
The Issue template is now not working.
I believe it should be in the `doc` folder which is similar to the Pull Request Template, and this may be the reason which lowered the coverage in `codecov.io`

**Comment by thomad74** [comment]
On it!

**Comment by thomad74** [comment]
I just renamed the issue template to the same conventions as the pull request template, and moved it to the same folder to try and increase code coverage. I created a pull request on the master branch that needs approval from 5 people who I assigned as reviewers on the PR. https://github.com/GatorEducator/gatorgrouper/pull/189

**Comment by Lancasterwu** [comment]
Thanks! @thomad74
