### ISSUE TITLE
Debugging and Refactoring the Current Python Code

### ISSUE THREAD

**Issue by Lancasterwu** [GatorEducator/gatorgrouper#184]
With PR #180, we can finally run the restructured `gatorgrouper`.  

However, there are still some bugs and bad designed python code.

The program was only refactored in this structure, some specific functions still looks terrible.

I want to assign @GatorEducator/team-lancaster and @GatorEducator/team-spencer (except @huangs1 and @ilikerustoo) to go over all code in details to improve them. 

"The refactored code should be clean, efficient, and maintainable code that is well documented"

Please create a branch following the style `enhance/debug-improve-YOURFILENAME`
Note that you should not put `.py` after `YOURFILENAME`.

To be organized, please comment under this Issue to claim the file you are going to work.

You should be responsible for having a good understanding of the file that you are assigned and be able to explain to other people.

😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 

-------------------------------------------------------------------------------------------------------
We now have:
* @thomad74 for `read_student_file.py`
* @ALEXANDERB82  for `group_scoring.py`
* @wattob for `group_random.py`
* @everitt-andrew  for `wgroup_rrobin.py`
* @reibelj for `parse_arguments.py`
* @Lancasterwu for `display.py`
* @yeej2 for `remove_absent_students.py` and `rebalance.py`
* @baldeosinghm   for `gatorgrouper.py`

There are only two configuration files left
* `defaults.py` - short
* `constants.py` - short

-------------------------------------------------------------------------------------------------------
😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 😄 😆 😊 😃 😏 

When ever you find a bug or bad designed code or some thing that does not make sense to you, please make a note under this issue and raise a new issue to clearly explain it.

For example: 

Comment under this issue: 

```
reibelj commented a day ago

I will look into `parse_arguments.py`

Issue #194 to fix a bug related to invalid group number
```

Sample Issue that you should raise: https://github.com/GatorEducator/gatorgrouper/issues/194

**Comment by ilikerustoo** [comment]
Could to be more specific in examples of what would need improving? This is probably low priority for now since we have the application finally up and running when PR #180 merges.

**Comment by baldeosinghm** [comment]
I agree with @ilikerustoo.  What files do you think are in need of urgent refactoring?

**Comment by Lancasterwu** [comment]
I will explain more details when we meet, and I am also going to add more explanation under this issue later today.

**Comment by everitt-andrew** [comment]
I will look at potential refactoring that can be done with `group_rrobin.py`

**Comment by wattob** [comment]
I will take a look at the functions within `group_random.py`

**Comment by reibelj** [comment]
I will look into 'parse_arguments.py'

**Comment by ALEXANDERB82** [comment]
I will look at `group_scoring.py`

**Comment by thomad74** [comment]
I will look at `read_student_file.py`

**Comment by baldeosinghm** [comment]
I will handle `gatorgrouper.py`

**Comment by baldeosinghm** [comment]
I recently spoke to Saejin, and `gatorgrouper.py` has no real need for refactoring.  The code works and there is nothing to really attend to.

**Comment by thomad74** [comment]
@ilikerustoo have you done work on the `read_student_file.py` and if so, have you committed this work so I can continue to add to it?

**Comment by ilikerustoo** [comment]
@thomad74 I have not. I apologize. I have been busy but I will look into this again soon.

**Comment by thomad74** [comment]
@ilikerustoo No problem, I was just wondering!

**Comment by baldeosinghm** [comment]
This issue was handled by PR #226

**Comment by baldeosinghm** [comment]
This issue was handled by PR #226
