### ISSUE TITLE
Rebalance.py is not used

### ISSUE THREAD

**Issue by yeej2** [GatorEducator/gatorgrouper#197]
# Description of the Issue

Based on #184 I found that `rebalance.py` found in the `utils` folder is not currently called anywhere. If we do not need this, I would suggest deleting it to avoid confusion.

### Assigned Developers

@Michionlion @huangs1 @Lancasterwu

**Comment by huangs1** [comment]
@yeej2 I don't see `rebalance.py` called anywhere either. Also, there are no test cases for that file. Furthermore, when I run `pipenv run pytest -x -s --cov-config pytest.cov --cov-report term-missing --cov`, it does not show that `rebalance.py` needs to be tested.
