### ISSUE TITLE
The GatorGrouper Logo isn't Displaying in FireFox Browser

### ISSUE THREAD

**Issue by Lancasterwu** [GatorEducator/gatorgrouper#201]
# Description of the Issue

## Add Detailed Comment with More Information

After [PR#155 Project Summary and Logo](https://github.com/GatorEducator/gatorgrouper/pull/155) is merged to the master, the logo isn't displaying in the `README.md` with the FireFox browser. However, it works perfectly with Google Chrome. I'm wondering if this is the issue due to the size of the logo.

## Steps to Reproduce Issue

Open https://github.com/GatorEducator/gatorgrouper with FireFox browser.

## Screenshot

![ssgg2](https://user-images.githubusercontent.com/31478979/53706144-d4072d00-3df6-11e9-897d-d7fdd5d66c99.png)

### Assigned Developers

@quigley-c @leonardoz15 @szklenskij

**Comment by shafferz** [comment]
This is most likely due to the file format being in `.svg`. Perhaps converting the file using [an online converter](https://svgtopng.com/) would fix it?

I'll test it, and put up a pull request if I can resolve the issue.

**Comment by leonardoz15** [comment]
Hi @shafferz , there is currently a branch [i-firefox-logo-bug](https://github.com/GatorEducator/gatorgrouper/tree/i-firefox-logo-bug) that @quigley-c was using to resize the logo, but I'm not sure if it was working or not.
