### ISSUE TITLE
Refactoring parse_arguments.py to remove exit statements

### ISSUE THREAD

**Issue by reibelj** [GatorEducator/gatorgrouper#202]
# Description of the Issue
Based on [Issue#184](https://github.com/GatorEducator/gatorgrouper/issues/184)
There are 2 exit statements in parse_arguments.py that are difficult to test. Refactoring may ease the testing process and increase the efficiency.

## Add Detailed Comment with More Information
Currently there are 2 exit statements on lines 93, and 104. These statements are difficult to test and could be more efficient. Slightly refactoring the program will allow to remove these exit statements and replace them with return statements. This will remove the requirement to test the statements and increase code coverage and efficiency of parse_args.py

### Assigned Developers
@Lancasterwu  @reibelj

**Comment by baldeosinghm** [comment]
Currently working on the return statements for `parse_arguments` and future test cases for it.

**Comment by baldeosinghm** [comment]
I removed the exit statements and changed them to return statements for better efficiency.  Code coverage for `parse_arguments.py` is now at 100%.

**Comment by reibelj** [comment]
Thanks for your contribution! @baldeosinghm
