### ISSUE TITLE
Refactor test cases to handle a generated csv file

### ISSUE THREAD

**Issue by reibelj** [GatorEducator/gatorgrouper#215]
# Description of the Issue

## Add Detailed Comment with More Information
Based on [Issue#209](https://github.com/GatorEducator/gatorgrouper/issues/209)
All test cases are currently passing, however, this is because the return value of "filenotfound"
This value is set to return true which allows all test cases to pass regardless of if a csv file exsists.

To fix this, we are going to utilize a fixture that will generate a csv file allowing us to remove the use of "filenotfound" and refactor the test cases to use this newly generated csv file.

### Assigned Developers
@reibelj  @thomad74  @wattob @Lancasterwu

**Comment by reibelj** [comment]
I created the branch refactor/all_test for us to work out of.

**Comment by wattob** [comment]
@Lancasterwu Have you already made changes for this issue in the branch `refactor/read_student_file`?

**Comment by reibelj** [comment]
Based on my discussion with @Lancasterwu not all test cases are in need of refactoring. We are going to focus on refactoring test_arguments.py  as  parse_arguments.py is the only file that requires the use of the csv generator. 

The refactoring of test_arugments is being handled by @baldeosinghm  and @Lancasterwu
