### ISSUE TITLE
Create a plan for deploying the web application

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#245]
# Description of the Issue

In order for our web application to be publicly available, we will need to figure out a way to deploy it.

## Add Detailed Comment with More Information
- Choose a hosting provider
- [Configure Travis for deployment](https://docs.travis-ci.com/user/deployment/)
- Deploy our web app

**Comment by sutterj** [comment]
This is the route that I would take: [Django App on AWS Elastic Beanstalk](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-django.html)

**Comment by corlettim** [comment]
Billy, Alex and I will figure this out in today's lab session

**Comment by ursowilliam** [comment]
Yup we are on it

**Comment by ursowilliam** [comment]
being worked on in the deploying-web-app branch

**Comment by sutterj** [comment]
@gkapfham @ursowilliam 
(GitHub AWS Integration)[https://aws.amazon.com/blogs/devops/automatically-deploy-from-github-using-aws-codedeploy/]
