### ISSUE TITLE
Implement group_graph parameters in command line interface

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#247]
# Description of the Issue

The command line interface for gatorgrouper should allow the user to pass in the following parameters to  `group_graph`:

- preferences (as a CSV file)
- preferences_weight
- preferences_weight_match
- objective_weights
- objective_measures

**Comment by Lancasterwu** [comment]
Couldn't we assume that users have all of these in the input CSV file already?

**Comment by aubreypc** [comment]
@Lancasterwu 
As of right now we can't use a single input CSV for this functionality because there is no system in place to distinguish between student skills and preferences in the file. 

However, we could possibly implement objective weights and objective measures as headers in the student data CSV.

**Comment by Lancasterwu** [comment]
Ok, seems not hard to do. I'll be able to take care of it.
