### ISSUE TITLE
No Input File Format Documented

### ISSUE THREAD

**Issue by quigley-c** [GatorEducator/gatorgrouper#292]
# Description of the Issue

Currently there is no documentation for what the input file should look like, that I can see.

## Add Detailed Comment with More Information

When attempting to run the tool it is important for the users to know what the input file formatting should look like. A sample input file or documentation describing what the input file should look like is needed to this extent.

## Steps to Reproduce Issue

Attempting to clone, setup, and run the command line tool from scratch by following the documentation in the README .

**Comment by aubreypc** [comment]
I'll write an explanation -- PR coming soon!
