### ISSUE TITLE
Implementing a GUI to Enhance Usability

### ISSUE THREAD

**Issue by shafferz** [GatorEducator/gatorgrouper#81]
I think that the implementation of a simple Python-based GUI script may help with the overall usability of the program. As it stands now, the biggest issues I've had with the software as-is have been in regards to setting up the program, and I believe that the implementation of a simple GUI may make that task trivial.

I was thinking of using the tkinter library in Python3, a simple and elegant GUI library for Python. @colezAC and I both have experience in the tkinter libraries. I was thinking of using the GUI to make the process of linking the Google Sheets/Forms with the program a trivial task.

**Comment by colezAC** [comment]
I have a GUI mostly built, it just won't run the program right now because it won't allow oauth to import. I only have this problem when trying to run it through the GUI.

**Comment by ZachAndrews98** [comment]
How is this enhancement going? Any progress made? Also, make sure any requirements for the system get added to the requirements.txt.

**Comment by shafferz** [comment]
@ZachAndrews98 We have the shell of the GUI itself, and are in the process of writing the functions to execute the code.

**Comment by ZachAndrews98** [comment]
Alright! Cool.

**Comment by shafferz** [comment]
The GUI has basic random/round-robin functionality as of now. We also have a desktop loader that launches the program from the desktop.

**Comment by ZachAndrews98** [comment]
Has the GUI been updated to allow for a number of groups/number of students in the groups to be specified?

**Comment by eltmanm** [comment]
what has been pushed so far runs the same as the main program with random. absentees would theoretically work with absentees working properly, though we havent been working with a complete fixed absentees function in our branch, and there are a few things that i think @shafferz has on his computer that hasnt been pushed yet.

**Comment by ZachAndrews98** [comment]
Anything that hasn't been pushed up should be pushed up and tested so that we can implement this feature.

**Comment by miller365** [comment]
Was this feature ever completed?

**Comment by eltmanm** [comment]
No it wasn't. Too many issues getting it to connect with the existing material

**Comment by gkapfham** [comment]
I'm going to close this issue as I do not think that it is a good idea to focus on the implementation of this feature. I would like to have a reliable command-line interface in production before we consider adding a graphical user interface. If this is an issue down the road, then we can open a new issue. Let me know if you disagree!
