### ISSUE TITLE
Use Pipenv for Dependency Management

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#95]
This project currently uses Pip for dependency management. However, this leads to the development and application dependencies currently being mixed in the same `requirements.txt` file. The project should be overhauled so that it now uses Pipenv instead and then the documentation should have new instructions for installing the dependencies and running the application and its test suite.

**Comment by gkapfham** [comment]
It is also important to point out that there are a lot of instructions about running the program in a virtual environment that are incorrect once we start to use Pipenv for managing the project's dependencies.

**Comment by gkapfham** [comment]
I should also point out that many of the instructions say that you should run the program by typing `python3`. This will be incorrect once we start to use Pipenv!

**Comment by ilikerustoo** [comment]
I have done part the pipenv implementation and will do documentation soon with other members

**Comment by Lancasterwu** [comment]
This issue has been resolved.
