### ISSUE TITLE
Restructure Project so That Modules are in a Separate Directory

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#96]
Currently, the main modules (i.e., Python files) are in the main directory for the project. However, this makes the main directory more cluttered. This application should be significantly restructured so that all of the Python modules are moved into a new package represented by a directory with a suitable name.

**Comment by aubreypc** [comment]
I have a proposal for the structure of the project:

- tests/
- src/
  - gatorgrouper.py
  - models/
    - group/
        - the existing `group_*.py` files, without the `group_`
  - views/
  - controllers/
        - the existing code for connecting to external services & API

This uses a [model - view - controller](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) design pattern. Roughly, models are where we define structures and functions to manage data, views are where we make different representations of the data, and controllers control the flow of data through the application and connect it to external services.

The MVC design pattern is used by many web frameworks (e.g. Django), so adopting it would make #94 more convenient if we decide to go ahead with that.

**Comment by gkapfham** [comment]
One quick comment based on the suggestion by @aubreypc: to learn more about the model-view-controller approach, you should also read Chapter 32 in the _Exercises in Programming Style_ book. The title of this chapter is "Trinity" and it explains the three entities that @aubreypc mentions. If we all read this chapter, then it will help us to better discuss the trade-offs of this approach.

One last quick note: if we reorganize the system, we will need to make sure that the existing test cases can still find the modules that they are designed to test. We may also need to change the imports at the top of many of the existing files. 

Finally, do others agree that this is a priority?

**Comment by aubreypc** [comment]
Here's an updated suggestion for the structure now that we are going ahead with Django -- how does this look, @quigley-c?

- tests/
- src/
  - models/
    - group/
      - group.py
      - modules for the grouping algorithms (or do these belong in controllers?)
    - user.py
    - course.py
    - assignment.py
  - views/
  - controllers/
  - static/
    - css/
    - js/
    - img/
  - templates/
- manage.py (Django's command-line interface)
- gatorgrouper.py (our command-line interface, if we choose to continue supporting this)

**Comment by quigley-c** [comment]
Update on the structure after our discussion:
- tests/
- src/
    - models/
        - user.py
        - course.py
        - assignment.py
    - views/
    - controllers/
    - static/
        - css/
        - js/
        - img/
    - templates/
- manage.py
- gatorgrouper.py

**Comment by barrezuetai** [comment]
What you guys currently have looks good, except the src/ and test/ probably need to be in the django directory.

This is the current Django directory structure
Root/
      -gatorgrouper/
              -migrations/
              -templates/
              -static/
              -admin.py
              -apps.py
              -models.py
              -tests.py
              -urls.py
              -views.py
      -gator_grouper/
              -settings.py
              -urls.py
              -wsgi.py
      -manage.py
      -db.sqlite3

**Comment by quigley-c** [comment]
Merged #151
