### ISSUE TITLE
Report Coverage Through PyTest and to CodeCov.io Instead

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#99]
The README contains instructions for running code coverage analysis that may not be standard. First, all of the dependencies should be installed with Pipenv. Second, coverage should be collected exclusively through a run of Pytest. Finally, details about reporting coverage to Coveralls do not need to be in the README file as they are instructions exclusively for use in Travis CI. I also suggest that we adopt CodeCov.io instead of using Coveralls.

**Comment by thomad74** [comment]
@huangs1 Have you completed the second half of this Issue regarding CodeCov.io? If so, @wattob and I are going to begin working on reporting the coverage through Pytest, and completing this task before the next laboratory session at the latest.

**Comment by huangs1** [comment]
@thomad74 Yes, I believe that my team has already finished the second half of this issue regarding CodeCov.io but the implementation has not yet been polished yet.

**Comment by thomad74** [comment]
@huangs1 Thank you for your response, we can reconvene later this week when both steps are completed and work on implementation, if you and your group would like.

**Comment by ilikerustoo** [comment]
I have successfully completed this but will review before confirming completely.

**Comment by Lancasterwu** [comment]
This issue has been resolved.
